version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - env.properties